### PR TITLE
added ipv4 test and improved pup scrape

### PR DESCRIPTION
**Pull request by sudocanttype**
Made the scrape more specific and added ipv4 supp, idk about ipv6

### CODE REVIEW

**Comment by BeyondMagic** [comment]
~yes i'm here too~

Please, change the priority order

**Comment by sudocanttype** [comment]
Aight, i can do that in a sec. Playing a game rn

**Comment by ayes-web** [comment]
> Why? It works as it rn, and those 3 divs it scrapes are ip addr specific
> @BeyondMagic

I guess It could theoretically be more efficient as IP search is uncommon

**Comment by BeyondMagic** [comment]
It is faster, I tested with how much priority can delay some common scrappers and it can get to 0.9s to 1.5s, depending on how much we add in tuxi, it can grow to at least to 2.5s. Scrapping of IP is extremely uncommon and it should go the bottom, we have to rework on the priority, but IP is not something that should be at the top at any occasion.

**Comment by sudocanttype** [comment]
Aight I'll do some testing and see where it can go

**Pull request merged**
